# Generated by Django 5.2 on 2025-04-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('CH', 'Chinese'), ('MX', 'Mexican'), ('UK', 'Ukrainian'), ('IT', 'Italian'), ('FF', 'Fast Food'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
